### ISSUE TITLE
docker support tigase7?

### ISSUE THREAD

**Issue by cena009** [tigase/tigase-xmpp-server-docker#8]
can had  docker images support tigase7,thanks

**Comment by woj-tek** [comment]
Hi,
Tigase XMPP Server 7 was release a long time ago, and we don't plan to provide docker images for it. We _highly_ recommend upgrade to the latest stable version (currently version 8) to get all the improvements and fixes that came with it.

If you really need docker image of version 7, you can create it on your own and base is on [8.0.0 `Dockerfile`](https://github.com/tigase/tigase-xmpp-server-docker/blob/master/8.0.0/Dockerfile) (it will require adjustments!)
